name: clima_col
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  location: ^7.0.0
  http: ^1.2.2
  intl: ^0.19.0
  flutter_screenutil: ^5.0.0
  permission_handler: ^11.3.1
  font_awesome_flutter: ^10.1.0
  responsive_builder: ^0.7.1
  cupertino_icons: ^1.0.8
  connectivity_plus: ^6.0.5
  geolocator: ^12.0.0
  geolocator_platform_interface: ^4.0.0
  shared_preferences: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1 # Agregar flutter_launcher_icons aquí

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png" # Ruta de tu ícono

flutter:
  uses-material-design: true
  assets:
    - assets/images/tu_imagen.jpg
    - assets/icon/tu_imagen.png # Asegúrate de incluir la carpeta de íconos
